// Preload Razorpay checkout script on page mount so payment pops up instantly
export const preloadRazorpay = () => {
  if (typeof window === "undefined" || window.Razorpay) return;
  const script = document.createElement("script");
  script.src = "https://checkout.razorpay.com/v1/checkout.js";
  script.async = true;
  document.body.appendChild(script);
};

// Simple utility function for Razorpay payment
export const openRazorpay = (options) => {
  return new Promise((resolve, reject) => {
    // Check if Razorpay script is already loaded
    if (window.Razorpay) {
      initializeRazorpay(options, resolve, reject);
    } else {
      const script = document.createElement("script");
      script.src = "https://checkout.razorpay.com/v1/checkout.js";
      script.onerror = () => {
        reject(new Error("Failed to load Razorpay script"));
      };
      script.onload = () => {
        initializeRazorpay(options, resolve, reject);
      };
      document.body.appendChild(script);
    }
  });
};

const initializeRazorpay = (options, resolve, reject) => {
  try {
    const rzpConfig = {
      key: import.meta.env.VITE_RAZORPAY_KEY,
      amount: options.amount,
      currency: options.currency || "INR",
      name: options.name || "Essmey Perfume",
      description: options.description || "Payment for your order",
      handler: function (response) {
        resolve(response);
      },
      prefill: {
        name: options.prefill?.name || "",
        email: options.prefill?.email || "",
        contact: options.prefill?.contact || "",
      },
      theme: {
        color: "#c08c53",
      },
      modal: {
        ondismiss: function () {
          reject(new Error("Payment cancelled by user"));
        },
      },
    };

    // Only pass order_id if it was generated by Razorpay API (not a mock ID)
    if (options.orderId && !options.orderId.startsWith("order_mock_")) {
      rzpConfig.order_id = options.orderId;
    }

    const rzp = new window.Razorpay(rzpConfig);

    rzp.on("payment.failed", function (response) {
      reject(new Error(response.error?.description || "Payment failed"));
    });

    rzp.open();
  } catch (error) {
    reject(error);
  }
};
