export const products = [
  {
    id: 1,
    name: "Midnight Allure",
    category: "women",
    price: 49.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "A seductive blend of jasmine, vanilla, and amber notes that unfolds throughout the evening. Perfect for those who appreciate a rich, feminine fragrance with lasting power.",
    notes: {
      top: ["Bergamot", "Black Currant", "Pink Pepper"],
      middle: ["Jasmine", "Rose", "Ylang-Ylang"],
      base: ["Vanilla", "Amber", "Patchouli"],
    },
    featured: true,
    bestSeller: true,
    new: false,
    stock: 15,
  },
  {
    id: 2,
    name: "Ocean Breeze",
    category: "men",
    price: 45.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "Experience the refreshing energy of coastal breezes with this vibrant masculine fragrance. Invigorating aquatic notes blend with woody undertones for a confident, clean scent.",
    notes: {
      top: ["Sea Salt", "Citrus", "Mint"],
      middle: ["Lavender", "Geranium", "Marine Accord"],
      base: ["Cedar", "Musk", "Ambergris"],
    },
    featured: true,
    bestSeller: false,
    new: true,
    stock: 20,
  },
  {
    id: 3,
    name: "Golden Aura",
    category: "unisex",
    price: 59.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "Elevate your presence with this luxurious unisex fragrance that balances warm saffron with cool iris. A versatile scent that adapts to your body chemistry for a truly personal experience.",
    notes: {
      top: ["Saffron", "Cardamom", "Lemon Zest"],
      middle: ["Iris", "Violet Leaves", "Cedarwood"],
      base: ["Oud", "Sandalwood", "Leather"],
    },
    featured: true,
    bestSeller: true,
    new: false,
    stock: 10,
  },
  {
    id: 4,
    name: "Velvet Rose",
    category: "women",
    price: 52.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "A sophisticated floral bouquet centered around the timeless elegance of rose. Delicate yet confident, this fragrance envelops you in a cloud of feminine charm and grace.",
    notes: {
      top: ["Raspberry", "Bergamot", "Pink Pepper"],
      middle: ["Rose Absolute", "Peony", "Magnolia"],
      base: ["White Musk", "Tonka Bean", "Honey"],
    },
    featured: false,
    bestSeller: true,
    new: false,
    stock: 8,
  },
  {
    id: 5,
    name: "Amber Wood",
    category: "men",
    price: 48.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "A bold, masculine fragrance that combines the warmth of amber with rich woody notes. Perfect for the confident man who makes a lasting impression wherever he goes.",
    notes: {
      top: ["Ginger", "Bergamot", "Mandarin"],
      middle: ["Cinnamon", "Nutmeg", "Cypress"],
      base: ["Amber", "Sandalwood", "Vetiver"],
    },
    featured: false,
    bestSeller: false,
    new: true,
    stock: 12,
  },
  {
    id: 6,
    name: "Citrus Bloom",
    category: "unisex",
    price: 42.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "A vibrant and refreshing blend of citrus notes that awakens the senses. This energizing scent is perfect for daily wear, providing a burst of freshness that lasts throughout the day.",
    notes: {
      top: ["Lemon", "Grapefruit", "Bergamot"],
      middle: ["Neroli", "Orange Blossom", "Green Tea"],
      base: ["White Musk", "Cedar", "Vetiver"],
    },
    featured: true,
    bestSeller: false,
    new: true,
    stock: 18,
  },
  {
    id: 7,
    name: "Mystique Noir",
    category: "women",
    price: 55.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "An enigmatic and alluring fragrance that captures the essence of mystery. Dark florals blend with spicy notes to create a scent that's as complex as it is captivating.",
    notes: {
      top: ["Black Pepper", "Plum", "Bergamot"],
      middle: ["Dark Rose", "Incense", "Saffron"],
      base: ["Oud", "Vanilla", "Amber"],
    },
    featured: false,
    bestSeller: true,
    new: false,
    stock: 7,
  },
  {
    id: 8,
    name: "Mountain Pine",
    category: "men",
    price: 47.99,
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg"],
    description:
      "Embrace the rugged outdoors with this invigorating scent inspired by forest landscapes. Pine and fir balsam create a crisp, natural fragrance that evokes strength and adventure.",
    notes: {
      top: ["Pine Needles", "Juniper Berry", "Lime"],
      middle: ["Fir Balsam", "Cypress", "Cedar"],
      base: ["Oakmoss", "Amber", "White Musk"],
    },
    featured: true,
    bestSeller: false,
    new: true,
    stock: 14,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah M.",
    location: "New York",
    rating: 5,
    text: "I've tried many perfumes over the years, but Essmey's handcrafted fragrances are truly special. Midnight Allure has become my signature scent - I get compliments every time I wear it!",
  },
  {
    id: 2,
    name: "James L.",
    location: "Chicago",
    rating: 5,
    text: "As someone who's particular about scents, I was blown away by the quality of Ocean Breeze. It's refreshing without being overwhelming, and the longevity is impressive for a handcrafted product.",
  },
  {
    id: 3,
    name: "Elena K.",
    location: "Miami",
    rating: 4,
    text: "Golden Aura is the perfect unisex fragrance - sophisticated and unique. I appreciate that these perfumes are handcrafted with such attention to detail. Would definitely recommend!",
  },
  {
    id: 4,
    name: "Michael T.",
    location: "Seattle",
    rating: 5,
    text: "The Mountain Pine fragrance transports me to the forest every time I wear it. Amazing how a scent can capture nature so perfectly. Great customer service too!",
  },
];
